### ISSUE TITLE
Toggle device toolbar and listen events

### ISSUE THREAD

**Issue by paqstd-dev** [duskload/react-device-detect#148]
Hi, I found one interesting feature. When I enable "Toggle device toolbar" in my deskop pc, "mobile device" works fine, the MobileView is shown. But when I turn off "Toggle device toolbar", everything that should be displayed as BrowserView is not displayed and I have to refresh the page manually. How can this problem be solved?

My code is something like this:
```
import * as React from 'react'
import { BrowserView, MobileView } from 'react-device-detect'

class MyComponent extends React.Component {
    // ...
    render () {
        return (
            <>
                <MobileView>Mobile</MobileView>
                <BrowserView>Browser</BrowserView>
            </>
        )
    }
}

export default MyComponent
```

**Comment by duskload** [comment]
This package use user-agent for getting info about mobiles. If you need to change your view depending on some condition, you'd better look something like `react-responsive`, which is using a sort of css media queries in js.

User-agent will only change view after page refresh, that's an expected behavior.
