### ISSUE TITLE
Samsung Note 3 (phone) and Lenovo Idea Tab3 - 7inch tablet not properly detected

### ISSUE THREAD

**Issue by DNikolic-Paycor** [duskload/react-device-detect#25]
Hi!
Devices Samsung Note 3 (phone) and Lenovo Idea Tab3 - 7inch tablet are not properly identified on different web browsers :
Android Phone:
<Opera (Mini)> Samsung Note 3 was as expected. 
<Firefox> Samsung Note 3 was not as expected. it was not detected as a phone.

Android Tablet:
<Chrome (default)>Lenovo Idea Tab3 - 7inch was not as expected. it was detected as a phone.
<Firefox> Lenovo Idea Tab3 - 7inch was as expected. it was not detected as a phone.
<Opera (Normal)>Lenovo Idea Tab3 - 7inch was not as expected. it was detected as a phone.

If needed i can provide additional logs.
Is there any chance to improve this?
Thanks in advance!

**Comment by duskload** [comment]
Hi @kicaUBUNTU, thanks for your report.

Honestly, it's there is a lot of this devices which are not handled properly, and addition each of them is very cumbersome. For now, I consider add a method which you can pass your devices to, which in turns, help library to recognize them.

When I have some news about it, I would post update here, but I'm not sure it would be soon, since I have a lot of work outside of this package.

**Comment by kicaUBUNTU** [comment]
Hey @duskload thanks for response!
