### ISSUE TITLE
Working with screen resize

### ISSUE THREAD

**Issue by Quadriphobs1** [duskload/react-device-detect#7]
I understand the package works and detect the screen when the page is loading but is there a way to also make the detection upon screen resize like when you use chrome inspect to change screen responsiveness. I have been trying to fix this async but don't seems to get maybe a little help would do

**Comment by duskload** [comment]
Since detection is based on user-agent, it has to be loaded or reloaded to switch its type (mobile to browser or visa versa).

I think you can achieve this by adding an event listener on 'resize' to your application which catches change of window innedWidth and innerHeight and trigger component rerender with shouldComponentUpdate.

But for now, I am don't have plans for adding of such a feature to this package.

Thanks for your report.
