### ISSUE TITLE
Huawei Devices are not returning mobileVendor and mobileModel

### ISSUE THREAD

**Issue by Keatooon** [duskload/react-device-detect#82]
console.log("mobileVendor", mobileVendor);
    console.log("mobileModel", mobileModel);

These 2 fields are returning "none" on Huawei Mate 20 Pro

Get UA is able to return this: getUA Mozilla/5.0 (Linux; Android 10; LYA-L29) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Mobile Safari/537.36

**Comment by duskload** [comment]
UAParser.js doesn't return model and vendor for a given mobile, you can check this http://faisalman.github.io/ua-parser-js/. Since I use `ua-parser-js` under the hood - it kind of expected. Even though it's clear that `LYA-L29` in UA string is a Huawei model, I'm not going to add check specifically for this model (because in this case, I would have to add manually some models for other phones, which is **a lot**. Not until I came up with a solution for such a cases.
